name: 🚀 Deploy website on new release

on:
  push:
    tags:
      - "*"

jobs:
  web-deploy:
    name: 🎉 Deploy to Cpanel
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - run: npm ci && npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5

        with:
          server: ${{secrets.ftp_server}}
          username: ${{ secrets.ftp_username}}
          password: ${{ secrets.ftp_password }}
          server-dir: ./
          local-dir: ./dist/public/
